### ISSUE TITLE
New/Delete : Malloc/Free

### ISSUE THREAD

**Issue by EdNutting** [uobteachingtechnologist/BristolSmartWatch#1]
Need to review the code to highlight all the places where "new" or "malloc" are used. This includes any implicit places such as string concatenation (e.g. "my string" + "my string" will cause 'new'/'malloc' to be used).

Then analyse the life of all the objects that arera created to find out when the pointers/references are no longer used / being overwritten. Find the points (if any) at which the last reference to objects are removed/lost. These points need to use the 'delete' keyword (for objects created with 'new' or string concat) or 'free' call if pointer allocated through malloc. This will free memory and stop memory leaks.

We can also use a simple library online called MemoryFree to display the current amount of free memory on the smartwatch during debugging. This will let us test various uses and see when memory leaks are occurring. See http://playground.arduino.cc/Code/AvailableMemory

**Comment by zenek13** [comment]
After analysing the code and fixing a small memory leak, the code now doesn't leak any memory.
